1. 1부터 10까지의 정수를 포함하는 NumPy 배열 생성하기


In [2]:
import numpy as np

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_array = (my_list)
my_array

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

2. 배열의 모든 요소에 5를 더하기


In [4]:
my_array += np.array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
my_array

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

3. 0에서 20까지의 짝수 배열 생성하기


In [40]:
my_array = np.arange(0, 22, 2)
print(my_array)

my_array = np.arange(22)
print(my_array)



[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


4. 두 배열의 덧셈 연산 수행하기


In [8]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
my_array_2 = np.array(my_list)
my_array_3 = my_array + my_array_2
my_array_3

array([ 2,  4,  6,  8, 10])

5. 5개의 무작위 수를 가진 배열 생성하기


In [ ]:
a = np.random.rand(2,3)
print(a)
# b = np.random.randint(2,5)
# print(b)

[[0.81511926 0.24010129 0.66066055]
 [0.05568549 0.66807476 0.72822675]]
2


6. 배열의 최대값과 최소값 찾기


In [ ]:
a = np.random.randint(1, 11, size = 10)
a

1

In [17]:
print(a)
print(np.min(a))
print(np.max(a))

[ 2  8  8  5  4  9  4 10  8  1]
1
10


7. 배열에서 2보다 큰 값만 선택하기


In [35]:
a = np.random.randint(1, 10, size = 10)
print(a, np.size(a))

[2 3 1 9 9 6 4 2 2 9] 10


In [36]:
b = a[a > 2]
print(b, np.size(b))


[3 9 9 6 4 9] 6


8. 1차원 배열을 2차원 배열로 변환하기


In [47]:
# reshape : 원하는 배열 형태로 변환하기. 단, 총 원소의 갯수가 맞아야 한다.
my_array = np.arange(20)
print(my_array, np.size(my_array))

a = my_array.reshape(2, 10)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 20
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


9. 배열의 평균, 중간값, 분산 구하기

In [50]:
a = np.arange(10)
print(a)
#print(np.min(a))
#print(np.max(a))

print(np.mean(a))
print(np.median(a))
print(np.var(a))


[0 1 2 3 4 5 6 7 8 9]
4.5
4.5
8.25


10. 두 개의 2차원 배열을 수직으로 쌓기

In [57]:
# np.vstack : vertical stack

a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,5)
print(a)
print(b)

c = np.vstack((a, b))
print(c)



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]


11. 배열을 랜덤하게 섞기

12. 배열의 모양(shape) 변경하기

13. 주어진 배열에서 각 요소의 제곱 구하기


14. 배열 안의 홀수만 선택하기


15. 3x3의 단위 행렬 생성하기


16. 1부터 9까지의 숫자로 3x3 배열 만들기


17. 배열에서 특정 인덱스의 값 변경하기


18. 조건에 따라 배열의 값 변경하기


19. 중복 요소가 없는 배열 생성하기


20. 배열의 역순으로 정렬하기


21. 배열의 전치 행렬 구하기


22. 두 배열의 요소별 곱셈


23. 특정 값의 인덱스 찾기


24. 배열의 통계 정보 구하기 (합계, 평균 등)


25. 배열을 1차원으로 평탄화하기


In [ ]:
# 평탄화 : 한줄로 나열한다. -> .flatten()


26. 특정 조건을 만족하는 배열의 길이 구하기


27. 배열에서 두 번째로 큰 값 찾기